console.log('francis')
console.log('has a girl friend')
console.log('her name is zimo')
console.log('they are fall in love')
console.log('they are going to marry')
console.log('they are going to have a baby')